### ISSUE TITLE
README wrong text

### ISSUE THREAD

**Issue by GosuSan** [NadyaNayme/NyusNecroJobGauge#4]
You forgot to change part of the README text when copy pasting it from your other project:

`To install Better Buff Bar copy & paste this link into Alt1's browser app:`

should probably be:

`To install Necro Job Gauge copy & paste this link into Alt1's browser app:`

Thanks for the tool, very nice work!

**Comment by NadyaNayme** [comment]
Yea, looks like I accidentally broke it back when I added the "If you don't have Alt1 installed here is how to get it" blurb. Not a huge deal  but might trip up a person or two who is skim reading so I'll get that fixed. Thanks for pointing it out.
